function plotFlightResults(results)
R2D=180/pi; t=results.Trajectory.t; x=results.Trajectory.x; d=results.DerivedQuantities; scenario=results.Scenario; ch=scenario.ControlHistory; delu=scenario.TestInputs; tuHis=ch.Times; deluHis=ch.Deltas; acTypeName=func2str(scenario.AircraftBuilder);
figure; subplot(2,2,1); plot(tuHis,R2D*deluHis(:,1)+R2D*delu(1),tuHis,R2D*deluHis(:,7)+R2D*delu(7)); xlabel('Time, s');ylabel('dE, dS, deg');grid;title('Pitch Control Test Inputs',acTypeName);legend('Elevator, dE','Stabilator, dS');
subplot(2,2,2);plot(tuHis,R2D*deluHis(:,2)+R2D*delu(2),tuHis,R2D*deluHis(:,3)+R2D*delu(3),tuHis,R2D*deluHis(:,5)+R2D*delu(5));xlabel('Time, s');ylabel('dA, dR, dAS, deg');grid;title('Lateral-Directional Control Test Inputs');legend('Aileron, dA','Rudder, dR','Asymmetric Spoiler, dAS');
subplot(2,2,3);plot(tuHis,deluHis(:,4)+delu(4));xlabel('Time, s');ylabel('dT, %');grid;title('Throttle Test Inputs, dT');subplot(2,2,4);plot(tuHis,R2D*deluHis(:,6)+R2D*delu(6));xlabel('Time, s');ylabel('dF, deg');grid;title('Flap Test Inputs');
figure;subplot(2,2,1);plot(t,x(:,1));xlabel('Time, s');ylabel('u, m/s');grid;title('Forward Body-Axis Velocity, u',acTypeName);subplot(2,2,2);plot(t,x(:,2));xlabel('Time, s');ylabel('v, m/s');grid;title('Side Body-Axis Velocity, v');subplot(2,2,3);plot(t,x(:,3));xlabel('Time, s');ylabel('w, m/s');grid;title('Normal Body-Axis Velocity, w');subplot(2,2,4);plot(t,x(:,1),t,x(:,2),t,x(:,3));xlabel('Time, s');ylabel('u, v, w, m/s');grid;title('Body-Axis Velocity Components');legend('u','v','w');
figure;subplot(3,2,1);plot(t,x(:,4));xlabel('Time, s');ylabel('x, m');grid;title('North Location, x',acTypeName);subplot(3,2,2);plot(t,x(:,5));xlabel('Time, s');ylabel('y, m');grid;title('East Location, y');subplot(3,2,3);plot(t,-x(:,6));xlabel('Time, s');ylabel('-z, m');grid;title('Altitude, -z');subplot(3,2,4);plot(sqrt(x(:,4).^2+x(:,5).^2),-x(:,6));xlabel('Ground Range, m');ylabel('Altitude, m');grid;title('Altitude vs. Ground Range');subplot(3,2,5);plot(x(:,4),x(:,5));xlabel('x, m');ylabel('y, m');grid;title('Ground Track');subplot(3,2,6);plot3(x(:,4),x(:,5),-x(:,6));xlabel('x, m');ylabel('y, m');zlabel('-z, m');grid;title('3D Flight Path');
figure;subplot(2,2,1);plot(t,R2D*x(:,7));xlabel('Time, s');ylabel('p, deg/s');grid;title('Body-Axis Roll Rate, p',acTypeName);subplot(2,2,2);plot(t,R2D*x(:,8));xlabel('Time, s');ylabel('q, deg/s');grid;title('Body-Axis Pitch Rate, q');subplot(2,2,3);plot(t,R2D*x(:,9));xlabel('Time, s');ylabel('r, deg/s');grid;title('Body-Axis Yaw Rate, r');subplot(2,2,4);plot(t,R2D*x(:,7),t,R2D*x(:,8),t,R2D*x(:,9));xlabel('Time, s');ylabel('p, q, r, deg/s');grid;title('Body-Axis Rate Components');legend('p','q','r');
figure;subplot(2,2,1);plot(t,R2D*x(:,10));xlabel('Time, s');ylabel('phi, deg');grid;title('Roll Attitude, phi',acTypeName);subplot(2,2,2);plot(t,R2D*x(:,11));xlabel('Time, s');ylabel('theta, deg');grid;title('Pitch Attitude, theta');subplot(2,2,3);plot(t,R2D*x(:,12));xlabel('Time, s');ylabel('psi, deg');grid;title('Yaw Attitude, psi');subplot(2,2,4);plot(t,R2D*x(:,10),t,R2D*x(:,11),t,R2D*x(:,12));xlabel('Time, s');ylabel('phi, theta, psi, deg');grid;title('Euler Angles');legend('phi','theta','psi');
figure;subplot(3,1,1);plot(t,d.AirspeedTAS);xlabel('Time, s');ylabel('TAS, m/s');grid;title('True AirSpeed (TAS), Vair',acTypeName);subplot(3,1,2);plot(t,d.Mach);xlabel('Time, s');ylabel('M, -');grid;title('Mach Number, M');subplot(3,1,3);plot(t,d.DynamicPressure);xlabel('Time, s');ylabel('qbar, N/m^2');grid;title('Dynamic Pressure, qbar');
figure;subplot(3,1,1);plot(t,d.AlphaDeg,t,d.BetaDeg);xlabel('Time, s');ylabel('Alpha, Beta, deg');grid;title('Aerodynamic Angles',acTypeName);legend('Angle of Attack, alpha','Sideslip Angle, beta');subplot(3,1,2);plot(t,d.FlightPathAngleDeg,t,d.HeadingAngleDeg);xlabel('Time, s');ylabel('Gamma, Psi, deg');grid;title('Flight Path Angles');legend('Flight Path Angle, gamma','Heading Angle, psi');subplot(3,1,3);plot(t,d.NormalLoadFactor);xlabel('Time, s');ylabel('nz, g');grid;title('Normal Load Factor Increment, nz, positive up');
if isfield(results.TrimResult,'History') && ~isempty(results.TrimResult.History), hist=results.TrimResult.History; idx=1:size(hist,2); figure;subplot(1,2,1);plot(idx,hist(1,:),idx,hist(2,:),idx,hist(3,:));grid;ylabel('dS, dT, dTheta');title(['Trim Parameters, ',acTypeName]);legend('Stabilator, dS, rad','Throttle, dT, 100%','dTheta, rad');subplot(1,2,2);semilogy(idx,hist(4,:));xlabel('Iterations');ylabel('Trim Cost');grid;title('Trim Cost');end
end
